#!/usr/bin/env ruby

require 'fileutils'

Dir.chdir(File.expand_path('..', __FILE__))

FileUtils.rm_r('temp') if File.directory?('temp')
FileUtils.mkdir_p('temp')

FileUtils.rm_r('out') if File.directory?('out')
FileUtils.mkdir_p('out')

if ARGV.include?('--from-source')
  Dir['source/*'].each do |dir|
    dst_dir = File.join('temp', File.basename(dir))
    FileUtils.cp_r(dir, dst_dir)
  end
else
  Dir.chdir('temp') do
    Dir['../*.tar.gz'].each do |file|
      system("gunzip -c '#{file}' | tar xopf -")
      old_dir = File.basename(file).gsub(/\.tar\.gz$/, '')
      new_dir = old_dir.gsub(/-2.+/, '')
      FileUtils.mv(old_dir, new_dir)
    end
  end
end

LIBRARIES = %w{SDL2 SDL2_image SDL2_mixer SDL2_net SDL2_ttf}.filter {|l| File.directory?("temp/#{l}")}

FileUtils.mkdir_p('out/include')
FileUtils.mkdir_p('out/lib')

intermediate_dir = File.expand_path("temp/intermediate")
FileUtils.mkdir_p(intermediate_dir)

LIBRARIES.each do |lib|
  args = [
    "-arch x86_64 -arch arm64",
    "-mmacosx-version-min=11"
  ]

  if lib != 'SDL2'
    args = [
      *args,
      "-I'#{intermediate_dir}/include/SDL2'",
      "-L'#{intermediate_dir}/lib'"
    ]
  end

  args = args.join(' ')

  Dir.chdir("temp/#{lib}") do
    system("CFLAGS=\"#{args}\" CXXFLAGS=\"#{args}\" LDFLAGS=\"#{args}\" ./configure --prefix=\"#{intermediate_dir}\"")
    system('make install')
  end

  if lib == 'SDL2'
    FileUtils.cp_r("#{intermediate_dir}/include/SDL2/.", "out/include")
  else
    FileUtils.cp("temp/#{lib}/#{lib.gsub('SDL2', 'SDL')}.h", "out/include")
  end

  full_lib_name = "lib#{lib}-2.0.0.dylib"

  FileUtils.cp(
    "#{intermediate_dir}/lib/#{full_lib_name}",
    'out/lib'
  )

  Dir.chdir('out/lib') do
    system("install_name_tool -id @rpath/#{full_lib_name} #{full_lib_name}")
    if lib != "SDL2"
      system("install_name_tool -change \"#{intermediate_dir}/lib/libSDL2-2.0.0.dylib\" @rpath/libSDL2-2.0.0.dylib #{full_lib_name}")
    end
    system("ln -s #{full_lib_name} lib#{lib}.dylib")
  end
end

