#!/usr/bin/env ruby

require 'net/http'

# Helper for downloading our files
def download(domain, path)
  target_file = File.basename path
  puts "Downloading #{domain}#{path} to #{target_file}"
  Net::HTTP.start(domain) do |http|
    resp = http.get path
    open(target_file, "wb") do |file|
      file.write(resp.body)
    end
  end
end

# Download each of our files
download 'libsdl.org', '/release/SDL2-2.0.3.tar.gz'
download 'libsdl.org', '/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz'
download 'libsdl.org', '/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz'
download 'libsdl.org', '/projects/SDL_net/release/SDL2_net-2.0.0.tar.gz'
download 'libsdl.org', '/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz'
